version: "3.7"

services:
  cassandra:
    image: cassandra
    container_name: cassandra_engine
    #deploy:
    #  restart_policy:
    #    condition: on-failure
    #    max_attempts: 3
    #healthcheck:
    #  test: cqlsh -u cassandra -p cassandra -k voicevista
    #  interval: 5s
    #  timeout: 10s
    #  retries: 6
    #volumes:
    #  - "./cassandra/cassandra-init.sh:/cassandra-init.sh"
    #command: "sh /cassandra-init.sh"
    ports:
      - 9042:9042

